# Сборка 2-х контейнеров, БД, Django проект
version: "3.8"

services:

  db:
    image: postgres:14.7-alpine
    container_name: db_postgres
    env_file: 
      - ./report_project/.env
    # внутри используется порт 5432 а пробрасывается на порт 5433
    ports:
      - 5433:5432
    volumes:
      - ${DATA_PATH}:/var/lib/postgresql/data

  report:
    build: .
    container_name: reports
    env_file:
      - ./report_project/.env
    command: python report_project/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db