# Generated by Django 4.2.13 on 2024-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="Номер заявки"),
                ),
                (
                    "order_state",
                    models.CharField(max_length=100, verbose_name="Состояние заявки"),
                ),
                (
                    "order_status",
                    models.CharField(max_length=100, verbose_name="Статус заявки"),
                ),
                (
                    "order_author",
                    models.CharField(max_length=100, verbose_name="Автор заявки"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(verbose_name="Дата создания заявки"),
                ),
                (
                    "processing_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания обработки"
                    ),
                ),
                (
                    "processing_duration_hours",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Время от создания заявки до конца обработки (в часах)",
                    ),
                ),
                (
                    "package_id",
                    models.CharField(max_length=100, verbose_name="ID пакета"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
